package net.xelpy.moreroad.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.xelpy.moreroad.MoreRoad;
import net.xelpy.moreroad.block.MoreRoadBlocks;

import java.util.function.Supplier;

public class MoreRoadCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MoreRoad.MODID);

    public static final Supplier<CreativeModeTab> MORE_ROAD_TAB = CREATIVE_MODE_TAB.register("more_road_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(MoreRoadItems.TEST.get()))
                    .title(Component.translatable("creativetab.moreroad.test_items"))
                    .displayItems((itemDisplayParameters, output) -> {
                        output.accept(MoreRoadItems.TEST);
                        output.accept(MoreRoadBlocks.A1A);
                        output.accept(MoreRoadBlocks.A1B);
                        output.accept(MoreRoadBlocks.A1C);
                        output.accept(MoreRoadBlocks.A1D);
                        output.accept(MoreRoadBlocks.A2A);
                        output.accept(MoreRoadBlocks.A2B);
                        output.accept(MoreRoadBlocks.A3);
                        output.accept(MoreRoadBlocks.A3A);
                        output.accept(MoreRoadBlocks.A3B);
                        output.accept(MoreRoadBlocks.A4);
                        output.accept(MoreRoadBlocks.A6);
                        output.accept(MoreRoadBlocks.A7);
                        output.accept(MoreRoadBlocks.A8);
                        output.accept(MoreRoadBlocks.A9);
                        output.accept(MoreRoadBlocks.A13A);
                        output.accept(MoreRoadBlocks.A13B);
                        output.accept(MoreRoadBlocks.A14);
                        output.accept(MoreRoadBlocks.A15A1);
                        output.accept(MoreRoadBlocks.A15A2);
                        output.accept(MoreRoadBlocks.A15B);
                        output.accept(MoreRoadBlocks.A15C);
                        output.accept(MoreRoadBlocks.A16);
                        output.accept(MoreRoadBlocks.A17);
                        output.accept(MoreRoadBlocks.A18);
                        output.accept(MoreRoadBlocks.A19);
                        output.accept(MoreRoadBlocks.A20);
                        output.accept(MoreRoadBlocks.A21A);
                        output.accept(MoreRoadBlocks.A23);
                        output.accept(MoreRoadBlocks.A24);
                        output.accept(MoreRoadBlocks.AB1);
                        output.accept(MoreRoadBlocks.AB2);
                        output.accept(MoreRoadBlocks.AB25);
                        output.accept(MoreRoadBlocks.AB3);
                        output.accept(MoreRoadBlocks.AB3A);
                        output.accept(MoreRoadBlocks.AB3B);
                        output.accept(MoreRoadBlocks.AB5);
                        output.accept(MoreRoadBlocks.AB4);
                        output.accept(MoreRoadBlocks.AB6);
                        output.accept(MoreRoadBlocks.AB7);
                        output.accept(MoreRoadBlocks.B0);
                        output.accept(MoreRoadBlocks.B1);
                        output.accept(MoreRoadBlocks.B2A);
                        output.accept(MoreRoadBlocks.B2B);
                        output.accept(MoreRoadBlocks.B2C);
                        output.accept(MoreRoadBlocks.B3);
                        output.accept(MoreRoadBlocks.B3A);
                        output.accept(MoreRoadBlocks.B4);
                        output.accept(MoreRoadBlocks.B5A);
                        output.accept(MoreRoadBlocks.B5B);
                        output.accept(MoreRoadBlocks.B5C);
                        output.accept(MoreRoadBlocks.B6A1);
                        output.accept(MoreRoadBlocks.B6A2);
                        output.accept(MoreRoadBlocks.B6A3);
                        output.accept(MoreRoadBlocks.B6D);
                        output.accept(MoreRoadBlocks.B7A);
                        output.accept(MoreRoadBlocks.B7B);
                        output.accept(MoreRoadBlocks.B8);
                        output.accept(MoreRoadBlocks.B9A);
                        output.accept(MoreRoadBlocks.B9B);
                        output.accept(MoreRoadBlocks.B9C);
                        output.accept(MoreRoadBlocks.B9D);
                        output.accept(MoreRoadBlocks.B9E);
                        output.accept(MoreRoadBlocks.B9F);
                        output.accept(MoreRoadBlocks.B9G);
                        output.accept(MoreRoadBlocks.B9H);
                        output.accept(MoreRoadBlocks.B9I);
                        output.accept(MoreRoadBlocks.B10A);
                        output.accept(MoreRoadBlocks.B11);
                        output.accept(MoreRoadBlocks.B12);
                        output.accept(MoreRoadBlocks.B13);
                        output.accept(MoreRoadBlocks.B13A);
                        output.accept(MoreRoadBlocks.B14_15);
                        output.accept(MoreRoadBlocks.B14_30);
                        output.accept(MoreRoadBlocks.B14_50);
                        output.accept(MoreRoadBlocks.B14_70);
                        output.accept(MoreRoadBlocks.B14_90);
                        output.accept(MoreRoadBlocks.B14_110);
                        output.accept(MoreRoadBlocks.B14_130);
                        output.accept(MoreRoadBlocks.B15);
                        output.accept(MoreRoadBlocks.B16);
                        output.accept(MoreRoadBlocks.B17);
                        output.accept(MoreRoadBlocks.B18A);
                        output.accept(MoreRoadBlocks.B18B);
                        output.accept(MoreRoadBlocks.B18C);
                        output.accept(MoreRoadBlocks.B19);
                        output.accept(MoreRoadBlocks.B21_1);
                        output.accept(MoreRoadBlocks.B21_2);
                        output.accept(MoreRoadBlocks.B21A1);
                        output.accept(MoreRoadBlocks.B21A2);
                        output.accept(MoreRoadBlocks.B21B);
                        output.accept(MoreRoadBlocks.B21C1);
                        output.accept(MoreRoadBlocks.B21C2);
                        output.accept(MoreRoadBlocks.B21A2);
                        output.accept(MoreRoadBlocks.B21D1);
                        output.accept(MoreRoadBlocks.B21D2);
                        output.accept(MoreRoadBlocks.B21E);
                        output.accept(MoreRoadBlocks.B22A);
                        output.accept(MoreRoadBlocks.B22B);
                        output.accept(MoreRoadBlocks.B22C);
                        output.accept(MoreRoadBlocks.B25);
                        output.accept(MoreRoadBlocks.B26);
                        output.accept(MoreRoadBlocks.B27A);
                        output.accept(MoreRoadBlocks.B27B);
                        output.accept(MoreRoadBlocks.B29);
                        output.accept(MoreRoadBlocks.B31);
                        output.accept(MoreRoadBlocks.B33_15);
                        output.accept(MoreRoadBlocks.B33_30);
                        output.accept(MoreRoadBlocks.B33_50);
                        output.accept(MoreRoadBlocks.B33_70);
                        output.accept(MoreRoadBlocks.B33_90);
                        output.accept(MoreRoadBlocks.B33_110);
                        output.accept(MoreRoadBlocks.B33_130);
                        output.accept(MoreRoadBlocks.B34);
                        output.accept(MoreRoadBlocks.B34A);
                        output.accept(MoreRoadBlocks.B35);
                        output.accept(MoreRoadBlocks.B39);
                        output.accept(MoreRoadBlocks.B40);
                        output.accept(MoreRoadBlocks.B41);
                        output.accept(MoreRoadBlocks.B42);
                        output.accept(MoreRoadBlocks.B43);
                        output.accept(MoreRoadBlocks.B44);
                        output.accept(MoreRoadBlocks.B45A);
                        output.accept(MoreRoadBlocks.B49);
                        output.accept(MoreRoadBlocks.C1A);
                        output.accept(MoreRoadBlocks.C1B);
                        output.accept(MoreRoadBlocks.C1C);
                    }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
